---
title: "Research Away Day Breakout summary"
author: ["Emma Rand", "Pen Holland", "Jillain Barlow"]
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
  bookdown::word_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
options(gargle_oauth_email = "emma.rand@york.ac.uk")
```

```{r}
library(tidyverse)
library(googlesheets4)
library(tidytext)
library(wordcloud)
```

```{r}
url <- "https://docs.google.com/spreadsheets/d/1XTMw6wkvgXiefBgOFnegOl6XBLUNFZBSbx1qqo9hwu8/edit?resourcekey#gid=95266269"
responses <- read_sheet(url, )
```


```{r}
responses %>% 
  group_by(`Which theme were you?`) %>%
  count() %>% 
  knitr::kable(caption = "Number of groups feeding back about each theme")
```

```{r}
tidy_resp <- responses %>% 
  group_by(`Which theme were you?`) %>% 
  mutate(ans_number = row_number()) %>% 
  ungroup() %>% 
  unnest_tokens(word, Summary)
```


```{r}
data(stop_words)
tidy_resp <- tidy_resp %>%
  anti_join(stop_words)

```
```{r}
tibble(Abbreivation = c("rstaff",
                        "tsstaff",
                        "artstaff",
                        "techstaff"),
       Meaning = c("Research staff",
                   "T&S Staff",
                   "ART Staff",
                   "Technical Staff")) %>% 
  knitr::kable(caption = "Key")
```


**A. How can all staff work together to improve the UG/PGT student research experience and outcomes?**
```{r}
tidy_resp %>%
  filter(`Which theme were you?` == "A. How can all staff work together to improve the UG/PGT student research experience and outcomes?") %>% 
  count(word) %>% 
  with(wordcloud(word, n,
                 min.freq = 2,
                 max.words = 100,
                 colors = brewer.pal(8, "Dark2")))
```


**B. How can all staff work together to improve professional training programmes?**
```{r}
tidy_resp %>%
  filter(`Which theme were you?` == "B. How can all staff work together to improve professional training programmes?") %>% 
  count(word) %>% 
  with(wordcloud(word, n, 
                 min.freq = 1,
                 max.words = 100, 
                 colors = brewer.pal(8, "Dark2")))
```

**C. Strategically, how do we create more interactions between staff groups?**
```{r}
tidy_resp %>%
  filter(`Which theme were you?` == "C. Strategically, how do we create more interactions between staff groups?") %>% 
  count(word) %>% 
  with(wordcloud(word, n,
                 min.freq = 1,
                 max.words = 100,
                 colors = brewer.pal(8, "Dark2")))
```



